{% set name = "pyobjc-framework-Quartz" %}
{% set version = "4.2.1" %}

package:
  name: pyobjc-framework-quartz
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11161f7c5d0602786f9b401183fe2f8e19291813d5d07fdfc0681b3e8ae00f07

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [not osx]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyobjc-framework-cocoa

test:
  imports:
    - Quartz
    - Quartz.CoreGraphics
    - Quartz.CoreVideo
    - Quartz.ImageIO
    - Quartz.ImageKit
    - Quartz.PDFKit
    - Quartz.QuartzComposer
    - Quartz.QuartzCore
    - Quartz.QuartzFilters
    - Quartz.QuickLookUI

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: 'Wrappers for the Quartz frameworks on Mac OS X'

extra:
  recipe-maintainers:
    - jschueller
